In [36]:
print("yeet")
def yeet(string):
    print(string)

yeet


In [37]:
asdf = {}
asdf['Megan'] = "Imagine Dragons"
asdf['Mikail'] = "Historical Fiction"
asdf["Aneesh"] = "A series of unfortunate events"
asdf["Charles"] = "Nanotech documentary"

for key in asdf:
    yeet(key + ", " + asdf[key])

Megan, Imagine Dragons
Mikail, Historical Fiction
Aneesh, A series of unfortunate events
Charles, Nanotech documentary


In [38]:
a = list(range(5, 10))
b = list(range(5))
c = zip(a, b)
yeet(a)
yeet(b)
yeet(list(c))


[5, 6, 7, 8, 9]
[0, 1, 2, 3, 4]
[(5, 0), (6, 1), (7, 2), (8, 3), (9, 4)]


In [23]:
import numpy as np
arr = np.array([[4, -6, 0],
                 [3, 8, -3],
                 [1, 2, -5],
                 [1, -1, 7],
                 [0, 1, 9]])

In [24]:
arr[4, 2]

9

In [35]:
arr[1:3,0]

array([3, 1])

In [86]:
arr[0:3, 1::-1]

array([[-6,  4],
       [ 8,  3],
       [ 2,  1]])

In [88]:
arr2 = np.arange(12).reshape(4, 3) + 1

In [89]:
arr3d = np.arange(8).reshape(2, 2, 2) + 1

In [94]:
arr3d

array([[[1, 2],
        [3, 4]],

       [[5, 6],
        [7, 8]]])

In [96]:
arr3d[0]

array([[1, 2],
       [3, 4]])

In [106]:
arr3d[:,1,0]

array([3, 7])

In [112]:
5**np.arange(5).reshape(5,1)

array([[  1],
       [  5],
       [ 25],
       [125],
       [625]])

In [125]:
%%timeit
for i in range(100_000):
    i**2

23.1 ms ± 940 µs per loop (mean ± std. dev. of 7 runs, 10 loops each)


In [128]:
%%timeit
x = np.arange(100_000)**2

373 µs ± 12.3 µs per loop (mean ± std. dev. of 7 runs, 1000 loops each)
