In [1]:
import numpy as np

In [5]:
x = np.array([1., 1.])

x /= np.linalg.norm(x)
x

array([0.70710678, 0.70710678])

In [6]:
y = np.array([1., 0.])

np.sum(x * y)

0.7071067811865475

In [9]:
x @ y

0.7071067811865475

In [10]:
np.sqrt(2) / 2.

0.7071067811865476

In [12]:
np.matmul(x, y)

0.7071067811865475

In [15]:
x = np.random.rand(4, 10)
x

array([[0.21367729, 0.84872153, 0.41427478, 0.34060311, 0.38516992,
        0.28338882, 0.53009219, 0.76978589, 0.97001513, 0.19236581],
       [0.17443859, 0.74028313, 0.20227454, 0.42664187, 0.66527953,
        0.14348482, 0.12273254, 0.19775792, 0.4659151 , 0.21263251],
       [0.72554949, 0.94576905, 0.93308272, 0.14461249, 0.71196536,
        0.71930332, 0.46189147, 0.00269608, 0.32831057, 0.83781651],
       [0.84796385, 0.47045059, 0.72124717, 0.07015522, 0.19426632,
        0.03750854, 0.09686318, 0.74669842, 0.95032766, 0.33339941]])

In [17]:
# shape 10, vector
# shape ,4 result

v = np.arange(10)

x @ v

array([23.71717195, 13.56501414, 22.64720452, 19.49930251])

In [25]:
M = 10
D = 15
N = 20
Q = 4

a1 = np.random.rand(M, D)
a2 = np.random.rand(D, N)
a3 = np.random.rand(N, Q)

assert (a1 @ a2 @ a3).shape == (M, Q)